from . import start
from . import help
from . import photo
from . import video
from . import file
from . import order
from . import call_back
from . import type_order
from . import up_message
from . import echo
from . import admin
